"""Prometheus telemetry middleware and metric registry for production serving."""

import time
from collections.abc import Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

try:
    from prometheus_client import (
        CONTENT_TYPE_LATEST,
        Counter,
        Histogram,
        generate_latest,
    )
    _PROMETHEUS_AVAILABLE = True
except ImportError:
    _PROMETHEUS_AVAILABLE = False


if _PROMETHEUS_AVAILABLE:
    # Prometheus Metrics Definitions
    INFERENCE_REQUESTS_TOTAL = Counter(
        "slm_inference_requests_total",
        "Total number of inference requests handled by FunctionCraft-SLM",
        ["endpoint", "tool_name", "status"],
    )

    INFERENCE_LATENCY_SECONDS = Histogram(
        "slm_inference_latency_seconds",
        "Inference latency distribution in seconds",
        ["endpoint"],
        buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
    )

    TOKENS_GENERATED_TOTAL = Counter(
        "slm_tokens_generated_total",
        "Estimated total tokens generated by the SLM",
        ["model_name"],
    )

    SCHEMA_VIOLATIONS_TOTAL = Counter(
        "slm_schema_violations_total",
        "Number of generated outputs that failed schema validation",
        ["tool_name"],
    )
else:
    INFERENCE_REQUESTS_TOTAL = None
    INFERENCE_LATENCY_SECONDS = None
    TOKENS_GENERATED_TOTAL = None
    SCHEMA_VIOLATIONS_TOTAL = None


class PrometheusMiddleware(BaseHTTPMiddleware):
    """Middleware for recording latency and request counts."""

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        if not _PROMETHEUS_AVAILABLE:
            return await call_next(request)

        start_time = time.perf_counter()
        response = await call_next(request)
        process_time = time.perf_counter() - start_time

        endpoint = request.url.path
        if endpoint in ["/v1/chat/completions", "/v1/tools/invoke"]:
            INFERENCE_LATENCY_SECONDS.labels(endpoint=endpoint).observe(process_time)

        return response


def get_metrics_response() -> Response:
    """Returns raw Prometheus formatted metrics for the /metrics endpoint."""
    if not _PROMETHEUS_AVAILABLE:
        return Response(content="# Prometheus client not installed\n", media_type="text/plain")
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)
